# Generated by Django 5.2 on 2026-04-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0030_remove_plan_price_invoice_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='experience',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='experienceType',
            field=models.CharField(choices=[('select', 'Select'), ('fresher', 'Fresher'), ('experienced', 'Experienced')], default='select', max_length=20),
        ),
    ]
