# Generated by Django 5.2 on 2026-04-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0031_jobseekerprofile_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='experienceType',
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('Fresher', 'Fresher'), ('Experienced', 'Experienced')], max_length=20, null=True),
        ),
    ]
